image: gradle:latest

pipelines:
  branches:
    develop:
      - step:
          script:
            - gradle clean build
    master:
      - step:
          script:
            - echo "gradle.publish.key=$GRADLE_PUBLISH_KEY" >> ~/.gradle/gradle.properties
            - echo "gradle.publish.secret=$GRADLE_PUBLISH_SECRET" >> ~/.gradle/gradle.properties
            - gradle clean build publish publishPlugins
