version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain innovenso --query authorizationToken --output text --region eu-west-1`
      - gradle clean build publish
  post_build:
    commands:
      - echo Build completed on `date`
